{
 "title": "PSA Aiops - Su Dashboard - Autoscaling # 01",
 "description": "Super simple dashboard showing an overview of Kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to Prometheus. Prometheus datasource can be chosen.",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "cpu request가 설정되지 않은 컨테이너",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(\r\n    (kube_pod_container_info unless on (container, pod) kube_pod_container_resource_requests{resource=\"cpu\"})\r\n    * on (pod) group_left(created_by_kind, created_by_name, namespace)\r\n    kube_pod_info\r\n) by(container, created_by_kind, created_by_name, namespace)"
    }
   ]
  },
  {
   "title": "memory request가 설정되지 않은 컨테이너",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(\r\n    (kube_pod_container_info unless on (container, pod) kube_pod_container_resource_requests{resource=\"memory\"})\r\n    * on (pod) group_left(created_by_kind, created_by_name, namespace)\r\n    kube_pod_info\r\n) by(container, created_by_kind, created_by_name, namespace)"
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_spec_target_metric (%)",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"cpu\"} ",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    },
    {
     "title": "memory_spec_target_metric (%)",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"memory\"} ",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    },
    {
     "title": "cluster_autoscaler_node_groups_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "cluster_autoscaler_node_groups_count",
       "legendFormat": "{{node_group_type}}"
      }
     ]
    },
    {
     "title": "Pod current_replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Autoscaler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count)\n"
      }
     ]
    },
    {
     "title": "Nodes available",
     "type": "stat",
     "description": "Shows the nodes which are ready as a percent of the total nodes",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})/sum(cluster_autoscaler_nodes_count)*100"
      }
     ]
    },
    {
     "title": "Is cluster safe to scale?",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale)"
      }
     ]
    },
    {
     "title": "Number of unscheduled pods",
     "type": "stat",
     "description": "Tells you if there are unscheduled pods",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_unschedulable_pods_count)",
       "legendFormat": " pods"
      }
     ]
    },
    {
     "title": "Last scaleDown activity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleDown\"})"
      }
     ]
    },
    {
     "title": "Last autoscale activity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\"})"
      }
     ]
    },
    {
     "title": "cluster_autoscaler_nodes_count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "cluster_autoscaler_nodes_count{state!=\"ready\"} > 0",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "cluster_autoscaler_unremovable_nodes_count ( no metric)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "cluster_autoscaler_unremovable_nodes_count{reason=\"10\"}"
      }
     ]
    },
    {
     "title": "Pod Total  , Node Total * 10",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum( sum(kube_pod_info) by ( namespace, pod) )\r\n",
       "legendFormat": "pod sum"
      },
      { "expr": "sum(kube_node_info) * 10", "legendFormat": "workernode sum  * 10" },
      {}
     ]
    },
    {
     "title": "cluster_autoscaler_unneeded_nodes_count ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "cluster_autoscaler_unneeded_nodes_count"
      }
     ]
    },
    {
     "title": "Pod activity",
     "type": "graph",
     "description": "Shows the evicted and unscheduled pods",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "none", "label": "Num Nodes" }
     ],
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_evicted_pods_total)",
       "legendFormat": "evicted pods"
      },
      {
       "expr": "sum(cluster_autoscaler_unschedulable_pods_count)",
       "legendFormat": "unscheduled pods"
      }
     ]
    },
    {
     "title": "Node Group Per Node Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "targets": [
      { "expr": "count(kube_node_info)", "legendFormat": "Total Node" },
      {
       "expr": "sum( kube_node_labels{} ) by ( label_eks_amazonaws_com_nodegroup)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}}"
      }
     ]
    },
    {
     "title": "kube_pod_status_phase pending",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{phase=\"Pending\"} > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node activity",
     "type": "graph",
     "description": "Shows the state of the nodes as scaling happens",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "none", "label": "Num Nodes" }
     ],
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})",
       "legendFormat": "ready"
      },
      {
       "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\"})",
       "legendFormat": "unready"
      },
      {
       "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\"})\n",
       "legendFormat": "not started"
      }
     ]
    },
    {
     "title": "Autoscaling activity",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "none", "label": "Num nodes" }
     ],
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_scaled_up_nodes_total)",
       "legendFormat": "scaled up total"
      },
      {
       "expr": "sum(cluster_autoscaler_unneeded_nodes_count)",
       "legendFormat": "unneeded nodes"
      },
      {
       "expr": "sum(cluster_autoscaler_nodes_count)\n",
       "legendFormat": "total nodes"
      }
     ]
    },
    {
     "title": "WorkerNode NoSchedule Metric countt (스케줄이 안되는 Node)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "sum( kube_node_spec_taint{ effect=~\"PreferNoSchedule|NoSchedule\"} ) by (instance)",
       "legendFormat": "{{instance}} {{effect}}"
      }
     ]
    },
    {
     "title": "node allocated memory",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "\r\n  sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)\r\n  / on (node)\r\n  kube_node_status_allocatable{resource=\"memory\"}\r\n  "
      }
     ]
    },
    {
     "title": "cpu node allocated",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "\r\n  sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)\r\n  / on (node)\r\n  kube_node_status_allocatable{resource=\"cpu\"}\r\n"
      }
     ]
    }
   ]
  }
 ]
}