{
 "title": "PSA Aiops - Su Dashboard - ArgoCD # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,2h,4h,6h,8h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"argocd-server-metrics\"})"
    }
   ]
  },
  {
   "title": "등록된 cluster",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 1 },
   "targets": [
    { "expr": "argocd_cluster_info - 0", "legendFormat": "{{server}}" },
    {
     "expr": "argocd_cluster_connection_status",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "repo request status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argocd_repo_pending_request_total",
     "legendFormat": "repo instance : {{instance}} // repo : {{repo}}"
    }
   ]
  },
  {
   "title": "Argocd application 정보",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Argocd application 정보 및 상태",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(\r\n    (argocd_app_info{sync_status=\"Synced\"} == 1)\r\n    or\r\n    ( (argocd_app_info{sync_status!=\"Synced\"} == 1) * 10 )\r\n)by(project,name,dest_server,dest_namespace,repo)"
      },
      {
       "expr": "sum(\r\n    (argocd_app_info{health_status=\"Healthy\"} == 1)\r\n    or\r\n    ( (argocd_app_info{health_status!=\"Healthy\"} == 1) * 10 )\r\n)by(project,name,dest_server,dest_namespace,repo)"
      },
      {
       "expr": "argocd_app_info{health_status!=\"Healthy\"} == 1"
      },
      {
       "expr": "time() - max_over_time(timestamp(changes(argocd_app_sync_total[$interval]) > 0) [1d:$interval])"
      }
     ]
    },
    {
     "title": "Sync history",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "changes(argocd_app_sync_total[1m])",
       "legendFormat": "{{project}} : {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation 횟수",
     "type": "timeseries",
     "description": "Argocd에서 cluster의 리소스 상태를 체크하는 횟수",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "increase(argocd_app_reconcile_count[$interval])",
       "legendFormat": "{{dest_server}}"
      }
     ]
    },
    {
     "title": "Pending kubectl run",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_kubectl_exec_pending) by (command)",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "K8s API request 횟수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_k8s_request_total[$interval])) by (name, verb, resource_kind)",
       "legendFormat": "{{name}} : {{verb}} {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-application-controller-metrics\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"argocd-application-controller-metrics\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reconciliation Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_bucket[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "배포 Cluster resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "ArgoCD cache에 존재하는 Cluster resource object 개수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "argocd_cluster_api_resource_objects",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "ArgoCD에서 모니터링하고 있는 Cluster resource 개수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      { "expr": "argocd_cluster_api_resources", "legendFormat": "{{server}}" }
     ]
    }
   ]
  },
  {
   "title": "Repo server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git request 횟수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total[$interval]))by(repo,request_type)",
       "legendFormat": "{{request_type}} : {{repo}}"
      }
     ]
    },
    {
     "title": "Git request duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(argocd_git_request_duration_seconds_bucket[$interval]))by(repo,request_type,le))",
       "legendFormat": "{{request_type}} : {{repo}}"
      }
     ]
    },
    {
     "title": "CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"argocd-repo-server-metrics\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-repo-server-metrics\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ArgoCD server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"argocd-server-metrics\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-server-metrics\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "gRPC service request",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{job=\"argocd-server-metrics\"}[$interval])) by (grpc_service, grpc_code, grpc_method) > 0",
       "legendFormat": "{{grpc_service}} : {{grpc_code}} : {{grpc_method}}"
      }
     ]
    },
    {
     "title": " Redis request result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_redis_request_total[$interval])) by (initiator)",
       "legendFormat": "{{initiator}} - total"
      },
      {
       "expr": "sum(increase(argocd_redis_request_total{failed=\"true\"}[$interval])) by (initiator)",
       "legendFormat": "{{initiator}} - fail"
      }
     ]
    }
   ]
  }
 ]
}