{
 "title": "PSA Aiops - Su Dashboard - Kubelet, Kube-proxy # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kubelet // Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 kubelet memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}\r\n* on (node) group_left(node_select)\r\nlabel_replace(\r\n    kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 kubelet CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])\r\n* on (node) group_left(node_select)\r\nlabel_replace(\r\n    kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet // Docker operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 docker operation 실행 rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(kubelet_docker_operations_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\"}[1m])) by (operation_type, node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    },
    {
     "title": "노드별 docker operation 실행 에러 rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(kubelet_docker_operations_errors_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\"}[1m])) by (operation_type, node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    },
    {
     "title": "노드별 docker operation duration rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(kubelet_docker_operations_duration_seconds_count{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, operation_type)\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    },
    {
     "title": "노드별 docker operation duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_docker_operations_duration_seconds_bucket{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, operation_type, le))\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet // Runtime operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 runtime operation 실행 rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(kubelet_runtime_operations_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\"}[1m])) by (operation_type, node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    },
    {
     "title": "노드별 runtime operation 실행 에러 rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(kubelet_runtime_operations_errors_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\"}[1m])) by (operation_type, node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    },
    {
     "title": "노드별 runtime operation duration rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(kubelet_runtime_operations_duration_seconds_count{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, operation_type)\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    },
    {
     "title": "노드별 runtime operation duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, operation_type, le))\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet // Pod 생성",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 pod 생성 rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(kubelet_pod_start_duration_seconds_count{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node)\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 pod 생성 duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_start_duration_seconds_bucket[1m]))by(node, le))\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet // Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 storage operation duration rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_operation_duration_seconds_count[1m]))by(node, operation_name, volume_plugin)\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{operation_name}} : {{volume_plugin}}"
      }
     ]
    },
    {
     "title": "노드별 storage operation 에러 rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_operation_errors_total[1m]))by(node, operation_name, volume_plugin)\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{operation_name}} : {{volume_plugin}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet // cgroup manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 cgroup manager duration rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(kubelet_cgroup_manager_duration_seconds_count{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\"}[1m])) by (operation_type, node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    },
    {
     "title": "노드별 cgroup manager duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, operation_type, le))\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{operation_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet // Pod Lifecycle Event Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 PLEG relist duration rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(kubelet_pleg_relist_duration_seconds_count{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\"}[1m])) by (node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 PLEG relist duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, le))\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 PLEG relist interval // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_interval_seconds_bucket{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, le))\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubelet // RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 RPC request rate // CODE : 2xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\", code=~\"2..\"}[1m])) by (node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : 2xx"
      }
     ]
    },
    {
     "title": "노드별 RPC request rate // CODE : 3xx, 4xx, 5xx",
     "type": "timeseries",
     "description": "3xx(리다이렉션) : 요청 완료를 위해 추가 작업 조치가 필요합니다.\n4xx(클라이언트 오류) : 요청의 문법이 잘못되었거나 요청을 처리할 수 없습니다.\n5xx(서버 오류) : 서버가 명백히 유효한 요청에 대한 충족을 실패했습니다.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\", code=~\"3..\"}[1m])) by (node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : 3xx"
      },
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\", code=~\"4..\"}[1m])) by (node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : 4xx"
      },
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kubelet\", metrics_path=\"/metrics\",node=~\"$node\", code=~\"5..\"}[1m])) by (node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}} : 5xx"
      }
     ]
    },
    {
     "title": "노드별 RPC request duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kubelet\", metrics_path=\"/metrics\"}[1m])) by (node, verb, le))\r\n* on (node) group_left(node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{verb}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube-proxy // Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 kube-proxy memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    process_resident_memory_bytes{job=\"kube-proxy\"}, \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)    \r\n* on (node_select)\r\nlabel_replace(\r\n    kube_node_info{}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 kube-proxy CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    rate(process_cpu_seconds_total{job=\"kube-proxy\"}[1m]), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)   \r\n* on (node_select)\r\nlabel_replace(\r\n    kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\"\r\n)",
       "legendFormat": "{{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube-proxy // Rule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 kube-proxy rule duration rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    rate(kubeproxy_sync_proxy_rules_duration_seconds_count{job=\"kube-proxy\"}[1m]), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 kube-proxy rule duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    histogram_quantile(0.99, sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket{job=\"kube-proxy\"}[1m])) by (instance, le)), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube-proxy // Network programming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 kube-proxy Network programming duration rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    rate(kubeproxy_network_programming_duration_seconds_count{job=\"kube-proxy\"}[1m]), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 kube-proxy programming duration // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    histogram_quantile(0.99, sum(rate(kubeproxy_network_programming_duration_seconds_bucket{job=\"kube-proxy\"}[1m])) by (instance, le)), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube-proxy // Kube-API request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 kube-proxy - Kube API request rate // CODE : 2xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"2..\"}[1m]))by(instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : 2xx"
      }
     ]
    },
    {
     "title": "노드별 kube-proxy - Kube API request rate // CODE : 3xx, 4xx, 5xx",
     "type": "timeseries",
     "description": "3xx(리다이렉션) : 요청 완료를 위해 추가 작업 조치가 필요합니다.\n4xx(클라이언트 오류) : 요청의 문법이 잘못되었거나 요청을 처리할 수 없습니다.\n5xx(서버 오류) : 서버가 명백히 유효한 요청에 대한 충족을 실패했습니다.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"3..\"}[1m]))by(instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : 3xx"
      },
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"4..\"}[1m]))by(instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : 4xx"
      },
      {
       "expr": "label_replace(\r\n    sum(rate(rest_client_requests_total{job=\"kube-proxy\",code=~\"5..\"}[1m]))by(instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : 5xx"
      }
     ]
    },
    {
     "title": "노드별 kube-proxy - Kube API request // SLO 99%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-proxy\"}[1m])) by (instance, verb, le)), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n)\r\n* on (node_select) group_left(node)\r\nlabel_replace( kube_node_info{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap(.*)\" )",
       "legendFormat": "{{node_select}} : {{verb}}"
      }
     ]
    }
   ]
  }
 ]
}