{
 "title": "PSA Aiops - Su Dashboard - K8S API # 01",
 "description": "Super simple dashboard showing an overview of Kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to Prometheus. Prometheus datasource can be chosen.",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API SERVER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "api-server cpu",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"apiserver\"}[5m])"
      }
     ]
    },
    {
     "title": "api-server memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"apiserver\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "api-server request-total [5m]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[5m])) by ( instance)",
       "legendFormat": "api server:  {{instance}}"
      }
     ]
    },
    {
     "title": "API Server HTTP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (code_resource:apiserver_request_total:rate5m > 0) by ( code)",
       "legendFormat": "HTTP : {{code}}"
      }
     ]
    },
    {
     "title": "api-server read http error",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(code_resource:apiserver_request_total:rate5m{code=~\"5.+\", verb=\"read\"} ) by (resource) / sum(code_resource:apiserver_request_total:rate5m{ verb=\"read\"} ) by (resource) \r\n",
       "legendFormat": "{{ resource }}"
      }
     ]
    },
    {
     "title": "api-server read http error",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(code_resource:apiserver_request_total:rate5m{code=~\"5.+\", verb=\"write\"} ) by (resource) / sum(code_resource:apiserver_request_total:rate5m{ verb=\"write\"} ) by (resource) \r\n",
       "legendFormat": "{{ resource }}"
      }
     ]
    },
    {
     "title": "apiserver_request_duration_seconds_sum [WATCH]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(5,sum(rate(apiserver_request_duration_seconds_sum{} [5m])) by( verb, resource) )\r\n",
       "legendFormat": "{{verb}} {{ resource }}"
      }
     ]
    },
    {
     "title": "apiserver_request_duration_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(apiserver_request_duration_seconds_sum{verb!=\"WATCH\"} [5m])) by( verb, resource) )\r\n",
       "legendFormat": "{{verb}} {{ resource }}"
      }
     ]
    },
    {
     "title": "apiserver_admission_controller_admission_duration_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "topk(10, sum(apiserver_admission_controller_admission_duration_seconds_sum{}) by (name, type) )",
       "legendFormat": "{{name}} {{type}}"
      }
     ]
    },
    {
     "title": "workqueue_adds_total",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_adds_total{endpoint=\"https\" }[5m])) by ( name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "apiserver_response_sizes_sum",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10,sum(apiserver_response_sizes_sum{endpoint=\"https\"}) by ( resource, verb))",
       "legendFormat": " {{verb}} - {{resource}} "
      }
     ]
    },
    {
     "title": "apiserver_request_total",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(apiserver_request_total{})by(resource,verb)",
       "legendFormat": "{{verb}} {{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "DS_PROMETHEUS",
   "collapsed": true,
   "panels": [
    {
     "title": "ETCD Object Only Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum( etcd_object_counts{resource!=\"events\"} )",
       "legendFormat": "Total : {{resource}}"
      }
     ]
    },
    {
     "title": "etcd request duration latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "ETCD Object Event Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "etcd_object_counts{resource=\"events\"}",
       "legendFormat": "instance : {{instance}} event : {{resource}}"
      }
     ]
    },
    {
     "title": "request dulation operator",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum( rate(etcd_request_duration_seconds_sum[5m]) ) by ( operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "ETCD Object Count Top 10",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10,sort_desc(sum(etcd_object_counts{resource!=\"events\"})by(resource)))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "etcd db total size in byte",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(etcd_db_total_size_in_bytes) by ( instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ETCD Opration , Type dulation",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10,  sum(rate(etcd_request_duration_seconds_sum{}[5m])) by (operation,type) )\r\n",
       "legendFormat": "operation : {{operation}}    ,  type : {{type}} "
      }
     ]
    }
   ]
  },
  {
   "title": "KUBE-SCHEDULER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  },
  {
   "title": "CoreDNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "concurrent_rejects",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_max_concurrent_rejects_total{}[5m]))",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Panic Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_panics_total{}[5m]))",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Upstream Health Check Fails",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_healthcheck_broken_total{}[5m]))",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "reload fail",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_reload_failed_total{}[5m]))",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "cpu total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{container=\"coredns\"}[5m]))",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "memory total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_max_usage_bytes{container=\"POD\", pod=~\"coredns-.+\"})",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Request Size ( Record Type)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum( coredns_dns_requests_total ) by ( type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Size Rate ( Record Type)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum( rate(coredns_dns_requests_total[5m] ) ) by ( type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request / Response Total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum( rate( coredns_dns_requests_total[5m]) )",
       "legendFormat": "Request"
      },
      {
       "expr": "sum( rate(  coredns_dns_responses_total [5m] )) ",
       "legendFormat": "Response"
      }
     ]
    },
    {
     "title": "response rate ( UDP )",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(coredns_dns_response_size_bytes_sum[5m])\r\n",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "cache   ( suceess / denial )",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(coredns_cache_entries) by ( instance, type )",
       "legendFormat": "{{instance}} -- {{type}} "
      }
     ]
    },
    {
     "title": "core_dns_panic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "coredns_panics_total", "legendFormat": "{{pod}}" },
      {
       "expr": "rate( coredns_panics_total{} [5m] )",
       "legendFormat": "{{pod}} :  Rate"
      }
     ]
    },
    {
     "title": "Responses  Latency (99,90,50) Rate 5m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{}[5m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(coredns_forward_request_duration_seconds_bucket{}[5m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(coredns_forward_request_duration_seconds_bucket{}[5m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Responses  Latency (99,90,50)  Rate 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(coredns_forward_request_duration_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(coredns_forward_request_duration_seconds_bucket{}[1m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  }
 ]
}