{
 "title": "PSA Aiops - Su Dashboard - Resource request customize - zum",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resource usage graph // rollout : container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage // rollout : container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max(\r\n    rate(container_cpu_usage_seconds_total{container!~\"POD|\" }[1m])\r\n    * on (pod, container) group_left(rollout)\r\n    kube_pod_container_info\r\n    * on (pod) group_left(rollout)\r\n    label_replace(\r\n        kube_pod_info{namespace!~\"argo-cd|argo-rollouts|default|kube-node-lease|kube-public|kube-system|monitor|monitoring|nginx-ingress|nginx-test|test\"}, \"rollout\", \"$1\", \"created_by_name\", \"(.*)-([^-]*)\"\r\n    )\r\n)by(container, rollout)",
       "legendFormat": "{{rollout}} : {{container}}"
      }
     ]
    },
    {
     "title": "Memory usage // rollout : container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(\r\n    container_memory_working_set_bytes{container!~\"POD|\" }\r\n    * on (pod, container) group_left(rollout)\r\n    kube_pod_container_info\r\n    * on (pod) group_left(rollout)\r\n    label_replace(\r\n        kube_pod_info{namespace!~\"argo-cd|argo-rollouts|default|kube-node-lease|kube-public|kube-system|monitor|monitoring|nginx-ingress|nginx-test|test\"}, \"rollout\", \"$1\", \"created_by_name\", \"(.*)-([^-]*)\"\r\n    )\r\n)by(container, rollout)",
       "legendFormat": "{{rollout}} : {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "30Days MAX resource Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "30일 최대 사용량",
     "type": "table",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "max_over_time(\r\n    max(\r\n        rate(container_cpu_usage_seconds_total{container!~\"POD|\" }[1m])\r\n        * on (pod, container) group_left(rollout)\r\n        kube_pod_container_info\r\n        * on (pod) group_left(rollout)\r\n        label_replace(\r\n            kube_pod_info{namespace!~\"argo-cd|argo-rollouts|default|kube-node-lease|kube-public|kube-system|monitor|monitoring|nginx-ingress|nginx-test|test\"}, \"rollout\", \"$1\", \"created_by_name\", \"(.*)-([^-]*)\"\r\n        )\r\n    )by(container, rollout)\r\n[30d:1h])"
      },
      {
       "expr": "max_over_time(\r\n    max(\r\n        container_memory_working_set_bytes{container!~\"POD|\"}\r\n        * on (pod, container) group_left(rollout)\r\n        kube_pod_container_info\r\n        * on (pod) group_left(rollout)        \r\n        label_replace(\r\n            kube_pod_info{namespace!~\"argo-cd|argo-rollouts|default|kube-node-lease|kube-public|kube-system|monitor|monitoring|nginx-ingress|nginx-test|test\"}, \"rollout\", \"$1\", \"created_by_name\", \"(.*)-([^-]*)\"\r\n        )\r\n    )by(container, rollout)\r\n[30d:1h])"
      },
      {
       "expr": "max(\r\n    kube_pod_container_resource_requests{resource=\"cpu\"}\r\n    * on (pod, container) group_left(rollout)\r\n    kube_pod_container_info\r\n    * on (pod) group_left(rollout)\r\n    label_replace(\r\n        kube_pod_info{namespace!~\"argo-cd|argo-rollouts|default|kube-node-lease|kube-public|kube-system|monitor|monitoring|nginx-ingress|nginx-test|test\"}, \"rollout\", \"$1\", \"created_by_name\", \"(.*)-([^-]*)\"\r\n    )\r\n)by(container, rollout)"
      },
      {
       "expr": "max(\r\n    kube_pod_container_resource_requests{resource=\"memory\"}\r\n    * on (pod, container) group_left(rollout)\r\n    kube_pod_container_info\r\n    * on (pod) group_left(rollout)\r\n    label_replace(\r\n        kube_pod_info{namespace!~\"argo-cd|argo-rollouts|default|kube-node-lease|kube-public|kube-system|monitor|monitoring|nginx-ingress|nginx-test|test\"}, \"rollout\", \"$1\", \"created_by_name\", \"(.*)-([^-]*)\"\r\n    )\r\n)by(container, rollout)"
      }
     ]
    }
   ]
  }
 ]
}