{
 "title": "PSA Aiops - Su Dashboard - Service Nginx # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_service_info{namespace=~\"$namespace\"},service)\n\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "controller_leader_election_status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_leader_election_status > 0",
     "legendFormat": "Ingress Controller"
    }
   ]
  },
  {
   "title": "IngressController Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(nginx_ingress_controller_config_hash))",
     "legendFormat": "Ingress Controller"
    }
   ]
  },
  {
   "title": "IngressController Connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{}[5m]))"
    }
   ]
  },
  {
   "title": "IngressController Process",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_num_procs)"
    }
   ]
  },
  {
   "title": "Ingress Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "service name : host name",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 15, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_ingress_path{namespace=~\"$namespace\", service_name=~\"$service\"}",
       "legendFormat": "[Port] : {{service_port}}  ----->   [k8s service] : {{service_name}}      ------------------->  [host] : {{host}}"
      }
     ]
    },
    {
     "title": "nginx_ingress_service_port",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
     "targets": [
      {
       "expr": "sum(kube_ingress_path) by (service_port)",
       "legendFormat": "service port : {{service_port}}"
      }
     ]
    },
    {
     "title": "Domain host count",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(sum(kube_ingress_path)by(host))",
       "legendFormat": "Domain host count"
      }
     ]
    },
    {
     "title": "nginx_ingress_service_port",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 16 },
     "targets": [
      {
       "expr": "sum(kube_ingress_tls) by (secret)",
       "legendFormat": "secret : {{secret}}"
      }
     ]
    },
    {
     "title": "Ingress Class Name",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 20 },
     "targets": [
      {
       "expr": "sum(kube_ingress_info{})by (ingressclass)",
       "legendFormat": "IngressClass Name : {{ingressclass}}"
      }
     ]
    },
    {
     "title": "nginx_process_connections",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{}[5m])) by (controller_pod)",
       "legendFormat": "{{controller_pod}}"
      }
     ]
    },
    {
     "title": "Nginx Pod Start Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(time() - nginx_ingress_controller_nginx_process_oldest_start_time_seconds)by (controller_pod)",
       "legendFormat": "{{controller_pod}}"
      }
     ]
    },
    {
     "title": "nginx_config_reload_day",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(time() -(nginx_ingress_controller_config_last_reload_successful_timestamp_seconds))by(controller_pod)",
       "legendFormat": "{{controller_pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Domain( WWW )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": " histogram_quantile(0.99,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le) )",
       "legendFormat": "P 99% {{host}}"
      },
      {
       "expr": " histogram_quantile(0.95,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le) )",
       "legendFormat": "P 95%"
      },
      {
       "expr": " histogram_quantile(0.90,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le) )",
       "legendFormat": "P 90%"
      },
      {
       "expr": " histogram_quantile(0.50,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le) )",
       "legendFormat": "P 50%"
      }
     ]
    },
    {
     "title": "Response Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": " histogram_quantile(0.99,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le,host) )",
       "legendFormat": "P 99% : {{host}}"
      },
      {
       "expr": " histogram_quantile(0.95,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le, host) )",
       "legendFormat": "P 95% : {{host}}"
      },
      {
       "expr": " histogram_quantile(0.90,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le, host) )",
       "legendFormat": "P 90% : {{host}}"
      },
      {
       "expr": " histogram_quantile(0.50,sum(rate(nginx_ingress_controller_response_duration_seconds_bucket{  exported_namespace=~\"$namespace\" ,  exported_service=~\"$service\",status=~\"20.+\"}[5m]) ) by  (le, host) )",
       "legendFormat": "P 50% : {{host}}"
      }
     ]
    },
    {
     "title": "Success Rate 2xx  (%) ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": " sum( rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\" , status=~\"2.+\" }[1m])  ) by ( ingress)\r\n / on (ingress )\r\n sum( rate( nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\" } [1m] )) by ( ingress) * 100",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Fail Rate ( 3xx, +4xx + 5xx (%) )",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": " sum( rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\" , status!~\"2.+\" }[1m])  ) by ( ingress)\r\n / on (ingress )\r\n sum( rate( nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\" } [1m] )) by ( ingress) * 100 ",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "HTTP 5xx Error",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum( rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\" , status=~\"5.+\" }[1m])  ) by ( ingress)\r\n ",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "HTTP 4xx Error",
     "type": "timeseries",
     "description": "Only containers with resource limits set are displayed.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum( rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\" , status=~\"4.+\" }[1m])  ) by ( ingress)\r\n ",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "HTTP  3xx State",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum( rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\" , status=~\"3.+\" }[1m])  ) by ( ingress)\r\n ",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_ssl_expire_time_seconds ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum( \r\n  time() - nginx_ingress_controller_ssl_expire_time_seconds{exported_namespace=~\"$namespace\"}\r\n  )by (host) ",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_request_size_sum",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_size_sum{exported_namespace=~\"$namespace\", exported_service=~\"$service\"}[5m])) by (host)",
       "legendFormat": "reqeust  :  {{host}}"
      }
     ]
    },
    {
     "title": "HTTP Request 중 시간 지연이 많은 서비스 ( request_dulation_sum / request_size_sum )",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\r\n  sum(rate(nginx_ingress_controller_request_duration_seconds_sum{status!~\"2.+\",exported_namespace=~\"$namespace\", exported_service=~\"$service\" }[5m])) by (host ) \r\n   /\r\n  ( sum(rate(nginx_ingress_controller_request_size_sum{exported_namespace=~\"$namespace\", exported_service=~\"$service\"}[5m])) by (host)  / 1000 )\r\n)   > 0\r\n",
       "legendFormat": "{{host}}"
      },
      {},
      {}
     ]
    },
    {
     "title": "nginx_ingress_controller_response_size_sum",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_response_size_sum{exported_namespace=~\"$namespace\", exported_service=~\"$service\"}[5m]))by(host)\r\n  \r\n",
       "legendFormat": "response : {{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx_ingress_cpu (container_cpu_usage_seconds_total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "\r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n  sum(rate(container_cpu_usage_seconds_total{container!~\"POD|\"}[5m])) by (pod) \r\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "nginx_ingress_cpu (container_cpu_usage_seconds_total)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum( \r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n  sum(rate(container_cpu_usage_seconds_total{container!~\"POD|\"}[5m])) by (pod) \r\n)",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "nginx_ingress_cpu_throttle",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n  sum(rate(container_cpu_cfs_throttled_seconds_total{container!~\"POD|\" }[5m])) by (pod) \r\n) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_memory_working_set_bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum( \r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n  sum( container_memory_working_set_bytes{container!~\"POD|\" }  ) by (pod) \r\n)",
       "legendFormat": "Memory"
      }
     ]
    },
    {
     "title": "ingress virtual memory byte",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_nginx_process_virtual_memory_bytes[5m]))\r\n",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "container_memory_working_set_bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "\r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n  sum( container_memory_working_set_bytes{container!~\"POD|\" }  ) by (pod) \r\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "nginx_process_resident_memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_nginx_process_resident_memory_bytes{}[5m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx_ingress_controller_request_size_sum",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_size_sum[5m]))\r\n  \r\n",
       "legendFormat": "Controller ResponseSize Sum"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_response_size_sum",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_response_size_sum[5m]))",
       "legendFormat": "Controller ResponseSize Sum"
      },
      {
       "expr": "sum(rate(nginx_ingress_controller_reqeust_size_sum[5m])) * -1",
       "legendFormat": "Controller RequestSize Sum"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_request_size_sum",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_size_sum[5m]))by(controller_pod)\r\n  \r\n",
       "legendFormat": "{{controller_pod}}"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_response_size_sum",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_response_size_sum[5m]))by(controller_pod)\r\n  \r\n",
       "legendFormat": "{{controller_pod}}"
      }
     ]
    },
    {
     "title": "container_network_transmit_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n   sum(rate(container_network_transmit_bytes_total{  interface=~\"et.+\"}[5m])) by(pod)\r\n)",
       "legendFormat": "Total Size"
      }
     ]
    },
    {
     "title": "container_network_receive_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\r\n    (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n   sum(rate(container_network_receive_bytes_total{  interface=~\"et.+\"}[5m])) by(pod)\r\n)\r\n  \r\n",
       "legendFormat": "Total Size"
      }
     ]
    },
    {
     "title": "container_network_transmit_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "\r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n   sum(rate(container_network_transmit_bytes_total{  interface=~\"et.+\"}[5m])) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "container_network_transmit_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "\r\n  (count(nginx_ingress_controller_config_hash ) by( pod) ) \r\n* on(pod) group_left() \r\n   sum(rate(container_network_transmit_bytes_total{  interface=~\"et.+\"}[5m])) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_ingress_upstream_latency_seconds_sum",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum( rate(nginx_ingress_controller_requests{exported_namespace=~\"$namespace\", exported_service=~\"$service\"}[2m]) ) by (status)",
       "legendFormat": "HTTP Status : {{status}}"
      }
     ]
    },
    {
     "title": "nginx_ingress_controller_ingress_upstream_latency_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": " sum( rate(nginx_ingress_controller_ingress_upstream_latency_seconds_sum[2m]) ) by (controller_pod) \r\n /\r\n sum( rate(nginx_ingress_controller_ingress_upstream_latency_seconds_count[2m]) ) by (controller_pod)  * 1000\r\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}