{
 "title": "PSA Aiops - Su Dashboard - Loki # 01",
 "description": "Universal and flexible dashboard for logging",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  { "title": "Log Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"})[$__interval])) by (stream)"
    }
   ]
  },
  { "title": "Live Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"$searchable_pattern\")[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"$searchable_pattern\")[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({namespace=~\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"$searchable_pattern\")[30s])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}