{
 "title": "PSA Aiops - Su Dashboard - Cluster # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "nodegroup",
    "query": {
     "query": "label_values(kube_node_labels, label_eks_amazonaws_com_nodegroup)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels{label_eks_amazonaws_com_nodegroup=~\"$nodegroup\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "요약", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "노드수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_eks_amazonaws_com_nodegroup=~\"$nodegroup\"})"
    }
   ]
  },
  {
   "title": "전체 CPU spec (core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{mode='system'})by(node))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 1, "x": 8, "y": 1 } },
  {
   "title": "CPU 사용률 (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster:node_cpu:ratio" }
   ]
  },
  {
   "title": "CPU 사용량 (core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 17, "y": 1 },
   "options": {
    "content": "</br></br></br>\n\n<font size=\"3\"> ← 현재 사용량 </font>\n</br></br></br></br>\n\n<font size=\"3\"> <div style=\"text-align: right\"> 예약 현황 →  </div> </font>\n\n"
   }
  },
  {
   "title": "총 CPU 예약 (core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "{{label_eks_amazonaws_com_nodegroup}}"
    }
   ]
  },
  {
   "title": "전체 Memory spec (bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "MEMORY 사용률 (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})\r\n/\r\nsum(node_memory_MemTotal_bytes)\r\n"
    }
   ]
  },
  {
   "title": "MEMORY 사용량 (bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})\r\n"
    }
   ]
  },
  {
   "title": "총 Memory 예약 (bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "{{label_eks_amazonaws_com_nodegroup}}"
    }
   ]
  },
  {
   "title": "Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 사용률 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "cluster:node_cpu:ratio", "legendFormat": "Total cpu ratio" }
     ]
    },
    {
     "title": "CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\"})",
       "legendFormat": "Total cpu usage core"
      }
     ]
    },
    {
     "title": "총 CPU 예약 (core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
       "legendFormat": "Total cpu request core"
      }
     ]
    },
    {
     "title": "MEMORY 사용률 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})\r\n/\r\nsum(node_memory_MemTotal_bytes)\r\n",
       "legendFormat": "Total memory ratio"
      }
     ]
    },
    {
     "title": "MEMORY 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})\r\n",
       "legendFormat": "Total memory usage bytes"
      }
     ]
    },
    {
     "title": "총 Memory 예약 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
       "legendFormat": "Total memory request bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU, Memory / 노드그룹($nodegroup) / 노드($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 CPU 사용률 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    instance:node_cpu:ratio, \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 16, "w": 2, "x": 11, "y": 3 },
     "options": {
      "content": "</br></br>\n<font size=\"10\", color=\"green\">CPU</font>\n</br></br>\n</br></br>\n\n<font size=\"3\"> ← 현재 사용량 </font>\n</br></br></br></br>\n\n<font size=\"3\"> <div style=\"text-align: right\"> 예약 현황 →  </div> </font>\n\n</br></br></br></br>\n\n<font size=\"1\", color=\"red\"> 오른쪽 예약 현황 대비 왼쪽 현재 사용량이 현저하게 작은 경우,\n각 pod의 resource request 튜닝 필요 </font>\n"
     }
    },
    {
     "title": "노드별 CPU 예약 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\r\n    sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)\r\n    / on (node)\r\n    kube_node_status_allocatable{resource=\"cpu\"} \r\n) * on (node) group_left(label_eks_amazonaws_com_nodegroup, node_select)\r\nlabel_replace( \r\n    kube_node_labels{label_eks_amazonaws_com_nodegroup=~\"$nodegroup\", node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"\"}) by(node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 CPU 예약 (core)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\r\n    sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)\r\n) * on (node) group_left(label_eks_amazonaws_com_nodegroup, node_select)\r\nlabel_replace( \r\n    kube_node_labels{label_eks_amazonaws_com_nodegroup=~\"$nodegroup\", node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 CPU throttle",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{container!=\"\"}[1m]))by(node)\r\n * on (node) group_left(label_eks_amazonaws_com_nodegroup, node_select)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 Memory 사용률 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    instance:node_memory_utilisation:ratio, \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 16, "w": 2, "x": 11, "y": 26 },
     "options": {
      "content": "</br></br>\n<font size=\"6\", color=\"green\">Memory</font>\n</br></br>\n</br></br>\n\n<font size=\"3\"> ← 현재 사용량 </font>\n</br></br></br></br>\n\n<font size=\"3\"> <div style=\"text-align: right\"> 예약 현황 →  </div> </font>\n\n</br></br></br></br>\n\n<font size=\"1\", color=\"red\"> 오른쪽 예약 현황 대비 왼쪽 현재 사용량이 현저하게 작은 경우,\n각 pod의 resource request 튜닝 필요 </font>\n"
     }
    },
    {
     "title": "노드별 Memory 예약 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\r\n    sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)\r\n    / on (node)\r\n    kube_node_status_allocatable{resource=\"memory\"} \r\n) * on (node) group_left(label_eks_amazonaws_com_nodegroup, node_select)\r\nlabel_replace( \r\n    kube_node_labels{label_eks_amazonaws_com_nodegroup=~\"$nodegroup\", node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 Memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"}) by(node), \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 Memory 예약 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\r\n    sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)\r\n) * on (node) group_left(label_eks_amazonaws_com_nodegroup, node_select)\r\nlabel_replace( \r\n    kube_node_labels{label_eks_amazonaws_com_nodegroup=~\"$nodegroup\", node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network / 노드그룹($nodegroup) / 노드($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 Network (eth receive)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(node_network_receive_bytes_total{device=~\"eth.*\"}[1m]))by(instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 Network drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(node_network_receive_drop_total{}[1m])) by(instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk / 노드그룹($nodegroup) / 노드($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 Disk 사용량 (GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    (node_filesystem_size_bytes{fstype !=\"tmpfs\", mountpoint !=\"boot\"} - node_filesystem_avail_bytes{fstype !=\"tmpfs\", mountpoint !=\"boot\"}), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 Disk 사용률 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    1 - (node_filesystem_avail_bytes{fstype !=\"tmpfs\", mountpoint !=\"boot\"} / node_filesystem_size_bytes{fstype !=\"tmpfs\", mountpoint !=\"boot\"}), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 Disk io time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum(rate(node_disk_io_time_seconds_total[1m])) by (instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 Disk io time weighted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    sum( rate(node_disk_io_time_weighted_seconds_total [1m])) by(instance), \"node_select\", \"$1-$2-$3-$4\", \"instance\", \"([0-9]*).([0-9]*).([0-9]*).([0-9]*):.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 임시 볼륨",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    kube_node_status_capacity{ resource=\"ephemeral_storage\" }, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume / 노드그룹($nodegroup) / 노드($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 aws-ebs 사용 개수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "label_replace(\r\n    volume_manager_total_volumes{state=\"actual_state_of_world\", plugin_name=\"kubernetes.io/aws-ebs\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)\r\n\r\n",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 PV 사용률",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes\r\n* on (persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}} // PVC : {{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "노드별 host path 사용 개수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "label_replace(\r\n    volume_manager_total_volumes{state=\"actual_state_of_world\", plugin_name=\"kubernetes.io/host-path\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)\r\n\r\n",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    },
    {
     "title": "노드별 empty dir 사용 개수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "label_replace(\r\n    volume_manager_total_volumes{state=\"actual_state_of_world\", plugin_name=\"kubernetes.io/empty-dir\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n) * on (node_select) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)\r\n\r\n",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{node_select}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Info(pod, spec) / 노드그룹($nodegroup) / 노드($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "노드별 파드 개수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    count(kube_pod_info)by(host_ip), \"node_ip\", \"$1\", \"host_ip\", \"(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_eks_amazonaws_com_nodegroup}} : {{host_ip}}"
      }
     ]
    },
    {
     "title": "노드 정보 및 현재 리소스 사용 현황",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    node_uname_info - 0, \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup, label_kubernetes_io_hostname)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(\r\n  sum(time() - node_boot_time_seconds)by(instance), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"\r\n) * on (node_ip)\r\nlabel_replace( \r\n  kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(\r\n  node_memory_MemTotal_bytes - 0, \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n  kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "label_replace(\r\n  count(node_cpu_seconds_total{mode='system'}) by (instance), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)"
      },
      {
       "expr": "label_replace(\r\n  1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)"
      },
      {
       "expr": "label_replace(\r\n  1 - (node_memory_MemAvailable_bytes/ (node_memory_MemTotal_bytes)), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)"
      }
     ]
    },
    {
     "title": "노드별 파드 정보 및 현재 리소스 사용 현황",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\r\n    kube_pod_info - 0, \"node_ip\", \"$1\", \"host_ip\", \"(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", pod!=\"\"}[1m]))by(pod)\r\n* on (pod) group_left(node_ip)\r\nlabel_replace(\r\n    kube_pod_info, \"node_ip\", \"$1\", \"host_ip\", \"(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})by(pod)\r\n* on (pod) group_left(node_ip)\r\nlabel_replace(\r\n    kube_pod_info, \"node_ip\", \"$1\", \"host_ip\", \"(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(time() - kube_pod_created)\r\n* on (pod) group_left(node_ip)\r\nlabel_replace(\r\n    kube_pod_info, \"node_ip\", \"$1\", \"host_ip\", \"(.*)\"\r\n) * on (node_ip) group_left(label_eks_amazonaws_com_nodegroup)\r\nlabel_replace( \r\n    kube_node_labels{node=~\"$node\"}, \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"ip-(.*)-(.*)-(.*)-(.*).ap.*\"\r\n)"
      }
     ]
    }
   ]
  }
 ]
}