{
 "title": "PSA Aiops - Su Dashboard - Namespace # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "workload_type",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, created_by_kind)"
    }
   },
   {
    "name": "workload_name",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$workload_type\"}, created_by_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"},  pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace 요약",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace pod 개수",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\"})by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace별 현재 CPU 사용량 (core), 점유율",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"POD\"}) by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace별 CPU 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container!=\"POD\"}) by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace별 현재 CPU request (core)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace별 현재 Memory 사용량 (bytes), 점유율",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace별 Memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Namespace별 현재 Memory request (bytes)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "컨테이너 cpu 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|\" }[1m])\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}} : {{container}}"
      }
     ]
    },
    {
     "title": "컨테이너 CPU request 대비 사용률 (%)",
     "type": "timeseries",
     "description": "Only containers with resource limits set are displayed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\" }[1m]) / on (container, pod) kube_pod_container_resource_requests{resource=\"cpu\"}\r\n* on (pod) group_left(created_by_kind, created_by_name, namespace) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}} : {{container}}"
      }
     ]
    },
    {
     "title": "pod cpu request limit",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$namespace\",  pod=~\"$pod\"}) / count(kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"$namespace\",  pod=~\"$pod\"})",
       "legendFormat": "cpu limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\",  pod=~\"$pod\"}) /count(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\",  pod=~\"$pod\"})",
       "legendFormat": "cpu request"
      }
     ]
    },
    {
     "title": "pod cpu throttle",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\"}[1m] ) /  increase(container_cpu_cfs_periods_total{namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\"}[1m] )\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}} : {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}} : {{container}}"
      }
     ]
    },
    {
     "title": "컨테이너 Memory request 대비 사용률 (%)",
     "type": "timeseries",
     "description": "Only containers with resource limits set are displayed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\",container!~\"POD|\", pod=~\"$pod\" } / on (container, pod) group_left(created_by_kind, created_by_name, namespace) kube_pod_container_resource_requests{resource=\"memory\"}\r\n* on (pod) group_left(created_by_kind, created_by_name, namespace) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}} : {{container}}"
      }
     ]
    },
    {
     "title": "컨테이너 Memory request, limit (GiB)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\",  pod=~\"$pod\"}) / count(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\",  pod=~\"$pod\"})",
       "legendFormat": "Memory Limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\",  pod=~\"$pod\"}) / count(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\",  pod=~\"$pod\"})",
       "legendFormat": "Memory Request"
      },
      {
       "expr": "avg(container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}\r\n) ",
       "legendFormat": "Memory AVG Use"
      }
     ]
    },
    {
     "title": "pod  count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\" }",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod Network Receive",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{ namespace=~\"$namespace\", pod=~\"$pod\", interface=~\"et.+\"}[5m])) by(pod)\r\n* on (pod) group_left(created_by_kind, created_by_name, namespace) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}}"
      }
     ]
    },
    {
     "title": "pod Network Transmit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{ namespace=~\"$namespace\", pod=~\"$pod\", interface=~\"et.+\"}[5m])) by(pod)\r\n* on (pod) group_left(created_by_kind, created_by_name, namespace) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod Disk Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\"}[5m]))by(pod)\r\n* on (pod) group_left(created_by_kind, created_by_name, namespace) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}}"
      }
     ]
    },
    {
     "title": "pod Disk Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\"}[5m])) by(pod)\r\n* on (pod) group_left(created_by_kind, created_by_name, namespace) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{namespace}} : {{created_by_kind}} : {{created_by_name}} : {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}