{
 "title": "PSA Aiops - Su Dashboard - Overview # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_spec_unschedulable * on (node) group_left(internal_ip) kube_node_info\r\n+ on (node, internal_ip)\r\nsum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})by(node) * 2 * on (node) group_left(internal_ip) kube_node_info",
     "legendFormat": "{{internal_ip}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_pod_status_phase{phase=\"Running\"}\r\n+ on (pod)\r\nkube_pod_status_phase{phase=\"Pending\"} * 2)\r\n* on (pod) group_left(host_ip) kube_pod_info",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "description": "ratio",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace( instance:node_cpu:ratio, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\" )",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "description": "ratio",
   "gridPos": { "h": 15, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace( instance:node_memory_utilisation:ratio, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\" )",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace( instance:node_network_transmit_bytes:rate:sum, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{node_ip}}"
    }
   ]
  }
 ]
}