{
 "title": "PSA Aiops - Su Dashboard - POD select # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "workload_type",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, created_by_kind)"
    }
   },
   {
    "name": "workload_name",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$workload_type\"}, created_by_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels, node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\", node=~\"$node\"},  pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font size=\"3\", color=\"aquamarine\">데이터 출력 에러 시 POD select # 02 대시보드를 사용하세요.</font>"
   }
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "컨테이너 cpu 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|\" }[1m])\r\n* on (pod) group_left(created_by_kind, created_by_name, node_select) \r\nlabel_replace(\r\n    kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}} : {{ pod }} : {{container}} // {{node_select}}"
      }
     ]
    },
    {
     "title": "컨테이너 CPU request 대비 사용률 (%)",
     "type": "timeseries",
     "description": "resource request가 설정된 컨테이너의 데이터만 표시합니다.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|\" }[1m]) / on (container, pod) kube_pod_container_resource_requests{resource=\"cpu\"}\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{ pod }} - {{container}}"
      }
     ]
    },
    {
     "title": "컨테이너 cpu throttle",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[1m] ) /  increase(container_cpu_cfs_periods_total{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[1m] )\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{node}} -- {{ pod }} - {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "컨테이너 memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}} : {{ pod }} : {{container}} // {{node_select}}"
      }
     ]
    },
    {
     "title": "컨테이너 Memory request 대비 사용률 (%)",
     "type": "timeseries",
     "description": "resource request가 설정된 컨테이너의 데이터만 표시합니다.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|\"} \r\n/ on (container, pod) group_left() kube_pod_container_resource_requests{resource=\"memory\"}\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{ pod }} - {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod Network Receive",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{ namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\", interface=~\"et.+\"}[5m])) by(pod)\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "pod Network Transmit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{ namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\", interface=~\"et.+\"}[5m])) by(pod)\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod Disk Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[5m])\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "pod Disk Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[5m])\r\n* on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent volume 사용률 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes\r\n* on (persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$pod\"}",
       "legendFormat": "{{namespace}} : {{pod}} // PVC : {{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Persistent volume 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes\r\n* on (persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$pod\"}",
       "legendFormat": "{{namespace}} : {{pod}} // PVC : {{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}