{
 "title": "PSA Aiops - Su Dashboard - POD select # 02",
 "tags": [
  "POD select #01에서 에러 발생시에만 사용 권장",
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "workload_type",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, created_by_kind)"
    }
   },
   {
    "name": "workload_name",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$workload_type\"}, created_by_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels, node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\", node=~\"$node\"},  pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font size=\"3\", color=\"aquamarine\">POD select # 01 대시보드에서 에러가 발생했을 때에만 사용하는 것을 권장합니다. (모니터링 시스템에 부하가 발생할 수 있습니다.)</font>"
   }
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "컨테이너 cpu 사용량 (core)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max( rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|\" }[1m]) )by(pod,container,node)\r\n* on (pod, node) group_left(created_by_kind, created_by_name, node_select) \r\nmax(label_replace(\r\n    kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}, \"node_select\", \"$1\", \"node\", \"ip-(.*).ap.*\"\r\n))by(created_by_kind,created_by_name,node,node_select,pod)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}} : {{ pod }} : {{container}} // {{node_select}}"
      }
     ]
    },
    {
     "title": "컨테이너 CPU request 대비 사용률 (%)",
     "type": "timeseries",
     "description": "resource request가 설정된 컨테이너의 데이터만 표시합니다.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max( rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|\" }[1m]) )by(container,pod, node)\r\n/ on (container, pod, node) max( kube_pod_container_resource_requests{resource=\"cpu\"} )by(pod,container, node)\r\n* on (pod) group_left(created_by_kind, created_by_name) \r\nmax(kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"})by(created_by_kind,created_by_name,pod)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}} : {{ pod }} : {{container}}"
      }
     ]
    },
    {
     "title": "컨테이너 cpu throttle",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max( increase(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[1m]) )by(pod,container,node)\r\n/ max( increase(container_cpu_cfs_periods_total{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[1m]) )by(pod,container,node)\r\n* on (pod, node) group_left(created_by_kind, created_by_name) \r\nmax( kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"} )by(created_by_kind,created_by_name,pod,container, node)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}} : {{ pod }} : {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "컨테이너 memory 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max( container_memory_working_set_bytes{namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"} )by(pod,container, node)\r\n* on (pod, node) group_left(created_by_kind, created_by_name) \r\nmax( kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"} )by(created_by_kind,created_by_name,pod, node)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}} : {{ pod }} : {{container}}"
      }
     ]
    },
    {
     "title": "컨테이너 Memory request 대비 사용률 (%)",
     "type": "timeseries",
     "description": "resource request가 설정된 컨테이너의 데이터만 표시합니다.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max( container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|\"} )by(pod,container, node)\r\n/ on (container, pod, node) group_left() \r\nmax( kube_pod_container_resource_requests{resource=\"memory\"} )by(pod,container, node)\r\n* on (pod, node) group_left(created_by_kind, created_by_name) \r\nmax( kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"} )by(created_by_kind,created_by_name,pod, node)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}} : {{ pod }} : {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod Network Receive",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{ namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\", interface=~\"et.+\"}[5m])) by(pod, node)\r\n* on (pod, node) group_left(created_by_kind, created_by_name) \r\nmax( kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"} )by(created_by_kind,created_by_name,pod, node)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "pod Network Transmit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{ namespace=~\"$namespace\", container!=\"\", pod=~\"$pod\", interface=~\"et.+\"}[5m])) by(pod, node)\r\n* on (pod, node) group_left(created_by_kind, created_by_name) \r\nmax( kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"} )by(created_by_kind,created_by_name,pod, node)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod Disk Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[5m]))by(pod,node)\r\n* on (pod,node) group_left(created_by_kind, created_by_name) \r\nmax( kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"} )by(created_by_kind,created_by_name,pod,node)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "pod Disk Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!~\"POD|\", pod=~\"$pod\"}[5m]))by(pod,node)\r\n* on (pod,node) group_left(created_by_kind, created_by_name) \r\nmax( kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"} )by(created_by_kind,created_by_name,pod,node)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent volume 사용률 (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes)by(persistentvolumeclaim,node)\r\n* on (persistentvolumeclaim,node) group_left(pod, namespace) \r\n(\r\n    max(kube_pod_info)by(pod,node,namespace)\r\n    * on (pod) group_left(persistentvolumeclaim)\r\n    max( kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$pod\"} )by(pod, persistentvolumeclaim)\r\n)",
       "legendFormat": "{{namespace}} : {{pod}} // PVC : {{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Persistent volume 사용량 (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(kubelet_volume_stats_used_bytes)by(persistentvolumeclaim,node)\r\n* on (persistentvolumeclaim,node) group_left(pod, namespace) \r\n(\r\n    max(kube_pod_info)by(pod,node,namespace)\r\n    * on (pod) group_left(persistentvolumeclaim)\r\n    max( kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$pod\"} )by(pod, persistentvolumeclaim)\r\n)",
       "legendFormat": "{{namespace}} : {{pod}} // PVC : {{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}