{
 "title": "PSA Aiops - Su Dashboard - Workload # 01",
 "tags": [
  "Copyrightⓒ. PSA AiOps HS&EV All Rights Reserved",
  "mzc_tm_aiops@megazone.com"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "workload_type",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, created_by_kind)"
    }
   },
   {
    "name": "workload_name",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$workload_type\"}, created_by_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "workload 파드 개수",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"})by(created_by_name)\r\n* on (created_by_name) group_left(created_by_kind) avg(kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"})by(created_by_kind, created_by_name)",
     "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "workload cpu 사용량 (평균)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(\r\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!~\"POD|\" }[1m])\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    },
    {
     "title": "workload CPU request 대비 사용률 (평균)",
     "type": "timeseries",
     "description": "Only containers with resource limits set are displayed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\r\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[1m]) / on (container, pod) kube_pod_container_resource_requests{resource=\"cpu\"}\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    },
    {
     "title": "workload cpu throttle (평균)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\r\n    increase(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", container!=\"\"}[1m] ) /  increase(container_cpu_cfs_periods_total{namespace=~\"$namespace\", container!=\"\"}[1m] )\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "workload memory 사용량 (평균)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(\r\n    container_memory_working_set_bytes{namespace=~\"$namespace\", container=\"\"}\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    },
    {
     "title": "workload Memory request 대비 사용률 (평균)",
     "type": "timeseries",
     "description": "Only containers with resource limits set are displayed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\r\n    rate(container_memory_working_set_bytes{namespace=~\"$namespace\"}[1m]) / on (container, pod) kube_pod_container_resource_requests{resource=\"memory\"}\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "workload Network Receive (평균)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(\r\n    sum(rate(container_network_receive_bytes_total{ namespace=~\"$namespace\", interface=~\"et.+\"}[5m])) by(pod)\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    },
    {
     "title": "workload Network Transmit (평균)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(\r\n    sum(rate(container_network_transmit_bytes_total{ namespace=~\"$namespace\", interface=~\"et.+\"}[5m])) by(pod)\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "workload Disk Read (평균)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(\r\n    rate(container_fs_reads_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!=\"\"}[5m])\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    },
    {
     "title": "workload Disk Write (평균)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(\r\n    rate(container_fs_writes_bytes_total{device=~\"/dev/.*\", namespace=~\"$namespace\", container!=\"\"}[5m])\r\n    * on (pod) group_left(created_by_kind, created_by_name) kube_pod_info{created_by_kind=~\"$workload_type\", created_by_name=~\"$workload_name\"}\r\n) by (created_by_kind, created_by_name)",
       "legendFormat": "{{created_by_kind}} : {{created_by_name}}"
      }
     ]
    }
   ]
  }
 ]
}